# This file is a template, and might need editing before it works on your project.
# This is the Gradle build system for JVM applications
# https://gradle.org/
# https://github.com/gradle/gradle
image: gradle:5.0-jdk11-slim

# Disable the Gradle daemon for Continuous Integration servers as correctness
# is usually a priority over speed in CI environments. Using a fresh
# runtime for each build is more reliable since the runtime is completely
# isolated from any previous builds.
variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  key: $CI_COMMIT_REF_NAME
  untracked: true
  paths:
    - .gradle/wrapper
    - .gradle/caches

build:
  stage: build
  script: gradle clean build
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build
      - .gradle

aliyun-fc-deploy:
  stage: deploy
  image: registry.cn-beijing.aliyuncs.com/zxkane/aliyun-fc-fun:2.7.2
  script:
    - >
      sigil -f template.tmpl
      USING_VPC=true VPC_ID=$VPC_ID VPC_SWITCH_IDS=$VPC_SWITCHER_IDS SECURITY_GROUP_ID=$SECURITY_GROUP_ID
      USING_LOG=true LOG_PROJECT=$LOG_PROJECT LOG_STORE=$LOG_STORE
      DD_TOKEN=$DD_TOKEN DD_AES_KEY=$DD_AES_KEY DD_CORPID=$DD_CORPID
      DTS_ENDPOINT=$DTS_ENDPOINT DTS_INSTANCE_NAME=$DTS_INSTANCE_NAME DTS_ACCESS_KEY=$DTS_ACCESS_KEY
      DTS_KEY_SECRET=$DTS_KEY_SECRET > template.yml
    - fun deploy
  only:
    - release
